// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2IvrBk3Jcwgfyf3LWY-G6qGI_ooWPYV4',
    appId: '1:104695689266:web:81726db583f2777a3acc2b',
    messagingSenderId: '104695689266',
    projectId: 'demoapp-31973',
    authDomain: 'demoapp-31973.firebaseapp.com',
    storageBucket: 'demoapp-31973.firebasestorage.app',
    measurementId: 'G-W05GB8DR8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUYSOFfkK_QKXtkuIf-zqxyx7QV4BmEjs',
    appId: '1:104695689266:android:93792a85ccbc8eca3acc2b',
    messagingSenderId: '104695689266',
    projectId: 'demoapp-31973',
    storageBucket: 'demoapp-31973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlUj153YNaVneAPNF9J8enkQ6o2f7GC-o',
    appId: '1:104695689266:ios:9ca841b8dd4e54803acc2b',
    messagingSenderId: '104695689266',
    projectId: 'demoapp-31973',
    storageBucket: 'demoapp-31973.firebasestorage.app',
    iosBundleId: 'com.example.whatsappCloneUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlUj153YNaVneAPNF9J8enkQ6o2f7GC-o',
    appId: '1:104695689266:ios:9ca841b8dd4e54803acc2b',
    messagingSenderId: '104695689266',
    projectId: 'demoapp-31973',
    storageBucket: 'demoapp-31973.firebasestorage.app',
    iosBundleId: 'com.example.whatsappCloneUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2IvrBk3Jcwgfyf3LWY-G6qGI_ooWPYV4',
    appId: '1:104695689266:web:4f9746e341552b043acc2b',
    messagingSenderId: '104695689266',
    projectId: 'demoapp-31973',
    authDomain: 'demoapp-31973.firebaseapp.com',
    storageBucket: 'demoapp-31973.firebasestorage.app',
    measurementId: 'G-513SRHKBR2',
  );
}
