// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzNTClAhw9PDRAfYx08Jkn5Qyy0iUc5I',
    appId: '1:575799565458:web:f16530dca25b34729d9a4b',
    messagingSenderId: '575799565458',
    projectId: 'logify1-78e9c',
    authDomain: 'logify1-78e9c.firebaseapp.com',
    storageBucket: 'logify1-78e9c.firebasestorage.app',
    measurementId: 'G-EBJ5Z5GL70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0kkH0NLCqpMRLipMw8PnbvL92af6-0o',
    appId: '1:575799565458:android:85a858aaf623ec9b9d9a4b',
    messagingSenderId: '575799565458',
    projectId: 'logify1-78e9c',
    storageBucket: 'logify1-78e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJv6GwQpOCgm-wpyfgEAnOBaAdlpVDF8g',
    appId: '1:575799565458:ios:8204175e76b36d9c9d9a4b',
    messagingSenderId: '575799565458',
    projectId: 'logify1-78e9c',
    storageBucket: 'logify1-78e9c.firebasestorage.app',
    iosBundleId: 'com.example.logify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhzNTClAhw9PDRAfYx08Jkn5Qyy0iUc5I',
    appId: '1:575799565458:web:decba04e177199849d9a4b',
    messagingSenderId: '575799565458',
    projectId: 'logify1-78e9c',
    authDomain: 'logify1-78e9c.firebaseapp.com',
    storageBucket: 'logify1-78e9c.firebasestorage.app',
    measurementId: 'G-64EHTXEEGC',
  );
}
